INSERT INTO `{prefix}class` VALUES ('1', 'Truyện tranh thiếu niên', 'juvenile', '0', '1', 'lists.html');
INSERT INTO `{prefix}class` VALUES ('2', 'Truyện tranh thiếu nữ', 'girl', '0', '2', 'lists.html');
INSERT INTO `{prefix}class` VALUES ('3', 'Truyện tranh thanh niên', 'Youth', '0', '3', 'lists.html');
INSERT INTO `{prefix}class` VALUES ('4', 'Truyện tranh thiếu nhi', 'children', '0', '4', 'lists.html');
INSERT INTO `{prefix}gift` VALUES ('1', 'Thức ăn mèo tình thương', '/attachment/gift/2020/02/23/202002230109475103.png', '1', 'Thức ăn mèo tình thương', '1', '0');
INSERT INTO `{prefix}gift` VALUES ('2', 'Mèo bí ngô', '/attachment/gift/2020/02/23/202002230110417724.png', '10', 'Mèo bí ngô', '2', '0');
INSERT INTO `{prefix}gift` VALUES ('3', 'Đồ chơi mèo', '/attachment/gift/2020/02/23/202002230110521793.png', '50', 'Đồ chơi mèo', '3', '0');
INSERT INTO `{prefix}gift` VALUES ('4', 'Len mèo', '/attachment/gift/2020/02/23/202002230111068216.png', '88', 'Len mèo', '4', '0');
INSERT INTO `{prefix}gift` VALUES ('5', 'Dây chuyền mèo', '/attachment/gift/2020/02/23/202002230111279507.png', '100', 'Dây chuyền mèo', '5', '0');
INSERT INTO `{prefix}gift` VALUES ('6', 'Giấy vệ sinh mèo', '/attachment/gift/2020/02/23/202002230111366816.png', '200', 'Giấy vệ sinh mèo', '6', '0');
INSERT INTO `{prefix}gift` VALUES ('7', 'Xe đua mèo', '/attachment/gift/2020/02/23/202002230112064988.png', '520', 'Xe đua mèo', '7', '0');
INSERT INTO `{prefix}gift` VALUES ('8', 'Biệt thự mèo', '/attachment/gift/2020/02/23/202002230112221466.png', '1314', 'Biệt thự mèo', '8', '0');
INSERT INTO `{prefix}type` VALUES ('1', 'Nhãn', '0', 'tags', '1', '0');
INSERT INTO `{prefix}type` VALUES ('2', 'Thể loại', '0', 'theme', '3', '1');
INSERT INTO `{prefix}type` VALUES ('3', 'Chất lượng', '0', 'quality', '4', '0');
INSERT INTO `{prefix}type` VALUES ('4', 'Khu vực', '0', 'city', '5', '1');
INSERT INTO `{prefix}type` VALUES ('5', 'Bản quyền', '0', 'copyright', '6', '0');
INSERT INTO `{prefix}type` VALUES ('6', 'Huyền bí', '1', 'tags', '1', '0');
INSERT INTO `{prefix}type` VALUES ('7', 'Phiêu lưu', '1', 'tags', '2', '0');
INSERT INTO `{prefix}type` VALUES ('8', 'Khoa học viễn tưởng', '1', 'tags', '3', '0');
INSERT INTO `{prefix}type` VALUES ('9', 'Chúa tể', '1', 'tags', '4', '0');
INSERT INTO `{prefix}type` VALUES ('10', 'Huyền bí', '1', 'tags', '5', '0');
INSERT INTO `{prefix}type` VALUES ('11', 'Trường học', '1', 'tags', '6', '0');
INSERT INTO `{prefix}type` VALUES ('12', 'Tu chân', '1', 'tags', '7', '0');
INSERT INTO `{prefix}type` VALUES ('13', 'Hài hước', '1', 'tags', '8', '0');
INSERT INTO `{prefix}type` VALUES ('14', 'Vượt thời gian', '1', 'tags', '9', '0');
INSERT INTO `{prefix}type` VALUES ('15', 'Hậu cung', '1', 'tags', '10', '0');
INSERT INTO `{prefix}type` VALUES ('16', 'Đam mỹ', '1', 'tags', '11', '0');
INSERT INTO `{prefix}type` VALUES ('17', 'Tình cảm', '1', 'tags', '12', '0');
INSERT INTO `{prefix}type` VALUES ('18', 'Bí ẩn', '1', 'tags', '13', '0');
INSERT INTO `{prefix}type` VALUES ('19', 'Kinh dị', '1', 'tags', '14', '0');
INSERT INTO `{prefix}type` VALUES ('20', 'Kinh chiến', '1', 'tags', '15', '0');
INSERT INTO `{prefix}type` VALUES ('21', 'Hành động', '1', 'tags', '16', '0');
INSERT INTO `{prefix}type` VALUES ('22', 'Fanmade', '1', 'tags', '17', '0');
INSERT INTO `{prefix}type` VALUES ('23', 'Thể thao', '1', 'tags', '18', '0');
INSERT INTO `{prefix}type` VALUES ('24', 'Tâm huyết', '1', 'tags', '19', '0');
INSERT INTO `{prefix}type` VALUES ('25', 'Hư cấu', '1', 'tags', '20', '0');
INSERT INTO `{prefix}type` VALUES ('26', 'Huyền bí', '1', 'tags', '21', '0');
INSERT INTO `{prefix}type` VALUES ('27', 'Ngọt ngào', '1', 'tags', '22', '0');
INSERT INTO `{prefix}type` VALUES ('28', 'Cổ trang', '1', 'tags', '23', '0');
INSERT INTO `{prefix}type` VALUES ('29', 'Cuộc sống', '1', 'tags', '24', '0');
INSERT INTO `{prefix}type` VALUES ('30', 'Người thật', '1', 'tags', '25', '0');
INSERT INTO `{prefix}type` VALUES ('31', 'Đô thị', '1', 'tags', '26', '0');
INSERT INTO `{prefix}type` VALUES ('32', 'Truyện tranh', '2', 'theme', '1', '1');
INSERT INTO `{prefix}type` VALUES ('33', 'Light novel', '2', 'theme', '2', '1');
INSERT INTO `{prefix}type` VALUES ('34', '4-koma', '2', 'theme', '3', '1');
INSERT INTO `{prefix}type` VALUES ('35', 'Sách minh họa', '2', 'theme', '4', '1');
INSERT INTO `{prefix}type` VALUES ('36', 'Tranh đơn', '2', 'theme', '5', '1');
INSERT INTO `{prefix}type` VALUES ('37', 'Truyện tranh ngắn', '2', 'theme', '6', '1');
INSERT INTO `{prefix}type` VALUES ('38', 'Ký kết', '3', 'quality', '1', '0');
INSERT INTO `{prefix}type` VALUES ('39', 'Đẳng cấp', '3', 'quality', '2', '0');
INSERT INTO `{prefix}type` VALUES ('40', 'Phổ biến', '3', 'quality', '3', '0');
INSERT INTO `{prefix}type` VALUES ('41', 'Người mới', '3', 'quality', '4', '0');
INSERT INTO `{prefix}type` VALUES ('42', 'Nội địa', '4', 'city', '1', '1');
INSERT INTO `{prefix}type` VALUES ('43', 'Hồng Kông và Đài Loan', '4', 'city', '2', '1');
INSERT INTO `{prefix}type` VALUES ('44', 'Hàn Quốc', '4', 'city', '3', '1');
INSERT INTO `{prefix}type` VALUES ('45', 'Nhật Bản', '4', 'city', '4', '1');
INSERT INTO `{prefix}type` VALUES ('46', 'Ra mắt', '5', 'copyright', '1', '0');
INSERT INTO `{prefix}type` VALUES ('47', 'Độc quyền', '5', 'copyright', '2', '0');
INSERT INTO `{prefix}book_class` VALUES ('1', 'Nam chủ', 'male', '0', '1', 'lists.html');
INSERT INTO `{prefix}book_class` VALUES ('2', 'Nữ chủ', 'girl', '0', '2', 'lists.html');
INSERT INTO `{prefix}task` VALUES ('1', '0', 'Kiểm tra hàng ngày', 'Mỗi ngày kiểm tra đều có thể nhận thưởng', '10', '0', '1');
INSERT INTO `{prefix}task` VALUES ('2', '0', 'Mời người dùng', 'Mỗi lần mời thành công 1 người sẽ nhận được thưởng tương ứng', '10', '1', '0');
INSERT INTO `{prefix}task` VALUES ('3', '0', 'Bình luận truyện tranh', 'Mỗi ngày bình luận truyện tranh có thể nhận thưởng', '5', '0', '3');
INSERT INTO `{prefix}task` VALUES ('4', '0', 'Lưu truyện tranh', 'Mỗi ngày lưu truyện tranh có thể nhận thưởng', '5', '0', '3');
INSERT INTO `{prefix}task` VALUES ('5', '0', 'Bình luận tiểu thuyết', 'Mỗi ngày bình luận tiểu thuyết có thể nhận thưởng', '5', '0', '3');
INSERT INTO `{prefix}task` VALUES ('6', '0', 'Lưu tiểu thuyết', 'Mỗi ngày lưu tiểu thuyết có thể nhận thưởng', '5', '0', '3');
